filebeat.inputs:
  # 로그 파일 수집 설정
  - type: filestream
    enabled: true
    paths:
      - /usr/share/elk/libs/*.log
    clean_removed: true  # 삭제된 로그 파일의 기록을 registry에서 제거
    close_inactive: 5m   # 5분 동안 로그 파일에 변화가 없다면 멈춤
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}' # 시간 형식으로 새로운 이벤트 판단
      negate: true
      match: after
    exclude_lines: ['^TRACE', '^GET', '^DEBUG'] # 불필요한 로그 제외

output.logstash:
  hosts: ["logstash:5044"] # Logstash 호스트와 포트 설정
  ssl.enabled: false # SSL 비활성화