version: '3.7'  # 파일 규격 버전
services:       # 실행하려는 컨테이너 정의
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - 9090:9090 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    command: # web.enable-lifecycle은 API 재시작 없이 설정파일들을 reload 가능하게 해줌
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    restart: always
    networks:
      - promnet

  prometheus-monitor:
    image: prom/prometheus
    container_name: prometheus-monitor
    volumes:
      - ./prometheus-monitor/config:/etc/prometheus
    ports:
      - 9091:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      resources:
        limits:
          memory: 1.5g # Prometheus Monitor 메모리 제한 설정
        reservations:
          memory: 512m # Prometheus Monitor 예약 메모리 설정
    restart: always
    networks:
      - promnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    volumes:
      - ./grafana/volume:/var/lib/grafana
    deploy:
      resources:  # Grafana 메모리 제한 추가
        limits:
          memory: 1g
        reservations:
          memory: 512m
    restart: always
    networks:
      - promnet

networks:
  promnet:
    driver: bridge
