## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

name: filebeat

filebeat.inputs:
  # 로그 파일 수집 설정
  - type: log
    enabled: true
    paths:
      - /home/ubuntu/build/libs/backend-server-*.log
    fields:
      public_ip: 52.78.176.0
    fields_under_root: true
    multiline:
      pattern: '^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'
      negate: true
      match: after
    #exclude_lines: ['^DEBUG'] # DEBUG 로그 제외

processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~

output.logstash: #Logstash로 데이터 전송
  hosts: ["logstash:5044"] # Logstash 호스트와 포트 설정
  username: filebeat_internal
  password: ${FILEBEAT_INTERNAL_PASSWORD}

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#
http: #Filebeat 상태 확인을 위한 HTTP 엔드포인트를 활성화
  enabled: true
  host: 0.0.0.0